using System;
using ToolBelt.Numerics;
using ToolBelt.Tests.Framework;

namespace ToolBelt.Tests.Numerics
{
    /// <summary>
    /// Grades the distribution functions against 40-digit references (DistributionReferenceData.cs, generated by
    /// scripts/gen-distribution-references.py with mpmath) in the regimes where double-precision libraries disagree:
    /// tails down to 1e-300, x near 0, fractional and enormous (1e9) degrees of freedom. Measured worst case when this
    /// was written: 8.5e-14 relative; the bound below leaves a little headroom.
    /// </summary>
    public sealed class DistributionReferenceTests
    {
        private const double Tolerance = 2e-13;

        public void AllReferenceValues()
        {
            int checkedRows = 0;
            foreach (var r in DistributionReferenceData.Rows)
            {
                double got = r.Fn switch
                {
                    "NormalCdf" => Distributions.NormalCdf(r.X, r.A, r.B),
                    "NormalQuantile" => Distributions.NormalQuantile(r.X, r.A, r.B),
                    "StudentTCdf" => Distributions.StudentTCdf(r.X, r.A),
                    "StudentTQuantile" => Distributions.StudentTQuantile(r.X, r.A),
                    "ChiSquareCdf" => Distributions.ChiSquareCdf(r.X, r.A),
                    "ChiSquareQuantile" => Distributions.ChiSquareQuantile(r.X, r.A),
                    "FCdf" => Distributions.FCdf(r.X, r.A, r.B),
                    "FQuantile" => Distributions.FQuantile(r.X, r.A, r.B),
                    _ => throw new InvalidOperationException("Unknown reference function " + r.Fn),
                };
                double rel = Math.Abs(got - r.Expected) / Math.Max(Math.Abs(r.Expected), double.Epsilon);
                Check.True(rel <= Tolerance,
                    $"{r.Fn}(x={r.X:R}; {r.A:R}, {r.B:R}): expected {r.Expected:R}, got {got:R} (rel {rel:E2})");
                checkedRows++;
            }
            Check.True(checkedRows > 200, "reference table present");
        }
    }
}
