"""Generates tests/ToolBelt.Tests/Quality/GaugeRRReferenceData.cs: reference results for Quality/GaugeRR.cs.

Usage: python scripts/gen-gauge-references.py   (needs numpy + scipy)
Independent route: sums of squares come from nested least-squares model fits (residual sum of squares of
intercept -> +part -> +operator -> +part:operator, dummy coded), not from the cell/marginal-mean formulas the C# uses;
p-values from scipy.stats.f.sf. Variance components then follow the standard expected-mean-square equations.
"""
import numpy as np
from scipy import stats

def dummies(levels, n):
    m = np.zeros((len(levels), n))
    for row, lv in enumerate(levels):
        if lv > 0:
            m[row, lv - 1] = 1.0
    return m

def rss(X, y):
    beta, *_ = np.linalg.lstsq(X, y, rcond=None)
    e = y - X @ beta
    return float(e @ e)

def analyze(data, alpha):
    p, o, r = data.shape
    y, part, op = [], [], []
    for i in range(p):
        for j in range(o):
            for k in range(r):
                y.append(data[i, j, k]); part.append(i); op.append(j)
    y = np.array(y); n = len(y)
    one = np.ones((n, 1))
    P = dummies(part, p - 1); O = dummies(op, o - 1)
    PO = np.column_stack([P[:, a] * O[:, b] for a in range(p - 1) for b in range(o - 1)])
    r0 = rss(one, y); r1 = rss(np.hstack([one, P]), y); r2 = rss(np.hstack([one, P, O]), y); r3 = rss(np.hstack([one, P, O, PO]), y)
    ss_p, ss_o, ss_i, ss_e = r0 - r1, r1 - r2, r2 - r3, r3
    df_p, df_o, df_i, df_e = p - 1, o - 1, (p - 1) * (o - 1), p * o * (r - 1)
    ms_p, ms_o, ms_i, ms_e = ss_p / df_p, ss_o / df_o, ss_i / df_i, ss_e / df_e
    p_int = stats.f.sf(ms_i / ms_e, df_i, df_e)
    if p_int <= alpha:
        p_part = stats.f.sf(ms_p / ms_i, df_p, df_i); p_op = stats.f.sf(ms_o / ms_i, df_o, df_i)
        v_rep = ms_e; v_int = max(0.0, (ms_i - ms_e) / r)
        v_op = max(0.0, (ms_o - ms_i) / (p * r)); v_part = max(0.0, (ms_p - ms_i) / (o * r))
        removed = False
    else:
        df_pool = df_i + df_e; ms_pool = (ss_i + ss_e) / df_pool
        p_part = stats.f.sf(ms_p / ms_pool, df_p, df_pool); p_op = stats.f.sf(ms_o / ms_pool, df_o, df_pool)
        v_rep = ms_pool; v_int = 0.0
        v_op = max(0.0, (ms_o - ms_pool) / (p * r)); v_part = max(0.0, (ms_p - ms_pool) / (o * r))
        removed = True
    v_grr = v_rep + v_op + v_int
    ndc = max(1, int(np.floor(1.41 * np.sqrt(v_part) / np.sqrt(v_grr))))
    return dict(ss=(ss_p, ss_o, ss_i, ss_e), p_int=p_int, p_part=p_part, p_op=p_op, removed=removed,
                v=(v_rep, v_op, v_int, v_part), ndc=ndc)

rng = np.random.default_rng(20261005)
cases = []
# (parts, operators, trials, part sd, operator sd, interaction sd, repeatability sd, alpha)
for spec in [(10, 3, 3, 1.0, 0.15, 0.0, 0.2, 0.05),
             (10, 3, 2, 1.0, 0.3, 0.25, 0.1, 0.05),
             (5, 2, 4, 0.5, 0.05, 0.0, 0.3, 0.25),
             (8, 4, 3, 2.0, 0.0, 0.4, 0.15, 0.05),
             (6, 3, 2, 0.05, 0.1, 0.0, 0.2, 0.05)]:
    p, o, r, sp, so, si, se, alpha = spec
    part = rng.normal(0, sp, p); op = rng.normal(0, so, o); inter = rng.normal(0, si, (p, o))
    data = np.round(10 + part[:, None, None] + op[None, :, None] + inter[:, :, None] + rng.normal(0, se, (p, o, r)), 4)
    cases.append((data, alpha, analyze(data, alpha)))

def f(v):
    return repr(float(v))

out = ["// <auto-generated> by scripts/gen-gauge-references.py (numpy least squares + scipy.stats.f). Do not edit by hand.",
       "namespace ToolBelt.Tests.Quality", "{", "    internal static class GaugeRRReferenceData", "    {",
       "        public sealed class Case", "        {",
       "            public double[,,] Data = null!;", "            public double Alpha;",
       "            public double SsPart, SsOperator, SsInteraction, SsRepeatability;",
       "            public double InteractionP, PartP, OperatorP;", "            public bool InteractionRemoved;",
       "            public double VarRepeatability, VarOperator, VarInteraction, VarPart;", "            public int Ndc;",
       "        }", "", "        public static readonly Case[] Cases =", "        {"]
for data, alpha, res in cases:
    p, o, r = data.shape
    rows = []
    for i in range(p):
        ops = []
        for j in range(o):
            ops.append("{ " + ", ".join(f(v) for v in data[i, j]) + " }")
        rows.append("{ " + ", ".join(ops) + " }")
    out.append("            new Case")
    out.append("            {")
    out.append("                Data = new double[,,] { " + ", ".join(rows) + " },")
    out.append(f"                Alpha = {f(alpha)},")
    ss = res["ss"]; v = res["v"]
    out.append(f"                SsPart = {f(ss[0])}, SsOperator = {f(ss[1])}, SsInteraction = {f(ss[2])}, SsRepeatability = {f(ss[3])},")
    out.append(f"                InteractionP = {f(res['p_int'])}, PartP = {f(res['p_part'])}, OperatorP = {f(res['p_op'])},")
    out.append(f"                InteractionRemoved = {'true' if res['removed'] else 'false'},")
    out.append(f"                VarRepeatability = {f(v[0])}, VarOperator = {f(v[1])}, VarInteraction = {f(v[2])}, VarPart = {f(v[3])},")
    out.append(f"                Ndc = {res['ndc']},")
    out.append("            },")
out += ["        };", "    }", "}"]
path = "tests/ToolBelt.Tests/Quality/GaugeRRReferenceData.cs"
with open(path, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(out) + "\n")
for _, alpha, res in cases:
    print(f"removed={res['removed']} p_int={res['p_int']:.4g} ndc={res['ndc']}")
